=== ealevchenko/FC/doc/medoc/J0210401.xsd
<?xml version="1.0" encoding="windows-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation>Довідка про зведені за добу підсумкові облікові дані щодо обсягів обігу (отримання/відпуску) та залишків пального на акцизному складі пального</xs:documentation>
	</xs:annotation>
	<xs:include schemaLocation="common_types.xsd"/>
	<xs:element name="DECLAR" type="DeclarContent"/>
	<xs:complexType name="DeclarContent">
		<xs:sequence>
			<xs:element name="DECLARHEAD" type="DHead"/>
			<xs:element name="DECLARBODY" type="DBody">
				<xs:unique name="UT1RXXXXG1">
					<xs:selector xpath="T1RXXXXG1"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT1RXXXXG2">
					<xs:selector xpath="T1RXXXXG2"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT1RXXXXG3S">
					<xs:selector xpath="T1RXXXXG3S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT1RXXXXG4">
					<xs:selector xpath="T1RXXXXG4"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT1RXXXXG5S">
					<xs:selector xpath="T1RXXXXG5S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT1RXXXXG6S">
					<xs:selector xpath="T1RXXXXG6S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT1RXXXXG7">
					<xs:selector xpath="T1RXXXXG7"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT1RXXXXG8">
					<xs:selector xpath="T1RXXXXG8"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT1RXXXXG9">
					<xs:selector xpath="T1RXXXXG9"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT1RXXXXG10">
					<xs:selector xpath="T1RXXXXG10"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT1RXXXXG11">
					<xs:selector xpath="T1RXXXXG11"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT2RXXXXG1">
					<xs:selector xpath="T2RXXXXG1"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT2RXXXXG2">
					<xs:selector xpath="T2RXXXXG2"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT2RXXXXG3S">
					<xs:selector xpath="T2RXXXXG3S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT2RXXXXG4">
					<xs:selector xpath="T2RXXXXG4"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT2RXXXXG5">
					<xs:selector xpath="T2RXXXXG5"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT2RXXXXG6">
					<xs:selector xpath="T2RXXXXG6"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT3RXXXXG1">
					<xs:selector xpath="T3RXXXXG1"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT3RXXXXG2">
					<xs:selector xpath="T3RXXXXG2"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT3RXXXXG3S">
					<xs:selector xpath="T3RXXXXG3S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT3RXXXXG4S">
					<xs:selector xpath="T3RXXXXG4S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT3RXXXXG5">
					<xs:selector xpath="T3RXXXXG5"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT3RXXXXG6">
					<xs:selector xpath="T3RXXXXG6"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT3RXXXXG7">
					<xs:selector xpath="T3RXXXXG7"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT4RXXXXG1">
					<xs:selector xpath="T4RXXXXG1"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT4RXXXXG2">
					<xs:selector xpath="T4RXXXXG2"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT4RXXXXG3S">
					<xs:selector xpath="T4RXXXXG3S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT4RXXXXG4">
					<xs:selector xpath="T4RXXXXG4"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT4RXXXXG5">
					<xs:selector xpath="T4RXXXXG5"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT5RXXXXG1">
					<xs:selector xpath="T5RXXXXG1"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT5RXXXXG2">
					<xs:selector xpath="T5RXXXXG2"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT5RXXXXG3S">
					<xs:selector xpath="T5RXXXXG3S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT5RXXXXG4">
					<xs:selector xpath="T5RXXXXG4"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT5RXXXXG5">
					<xs:selector xpath="T5RXXXXG5"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT5RXXXXG6">
					<xs:selector xpath="T5RXXXXG6"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT5RXXXXG7">
					<xs:selector xpath="T5RXXXXG7"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT5RXXXXG8">
					<xs:selector xpath="T5RXXXXG8"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT5RXXXXG9">
					<xs:selector xpath="T5RXXXXG9"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT5RXXXXG10">
					<xs:selector xpath="T5RXXXXG10"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT6RXXXXG1">
					<xs:selector xpath="T6RXXXXG1"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT6RXXXXG2">
					<xs:selector xpath="T6RXXXXG2"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT6RXXXXG3S">
					<xs:selector xpath="T6RXXXXG3S"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT6RXXXXG4">
					<xs:selector xpath="T6RXXXXG4"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT6RXXXXG5">
					<xs:selector xpath="T6RXXXXG5"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT6RXXXXG6">
					<xs:selector xpath="T6RXXXXG6"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT6RXXXXG7">
					<xs:selector xpath="T6RXXXXG7"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
				<xs:unique name="UT6RXXXXG8">
					<xs:selector xpath="T6RXXXXG8"/>
					<xs:field xpath="@ROWNUM"/>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DHead">
		<xs:sequence>
			<xs:element name="TIN" type="DGLong"/>
			<xs:element name="C_DOC" type="xs:string" fixed="J02"/>
			<xs:element name="C_DOC_SUB" type="xs:string" fixed="104"/>
			<xs:element name="C_DOC_VER" type="xs:string" fixed="1"/>
			<xs:element name="C_DOC_TYPE" type="xs:nonNegativeInteger"/>
			<xs:element name="C_DOC_CNT" type="xs:nonNegativeInteger"/>
			<xs:element name="C_REG" type="DGsti"/>
			<xs:element name="C_RAJ" type="DGsti"/>
			<xs:element name="PERIOD_MONTH" type="DGMonth"/>
			<xs:element name="PERIOD_TYPE" type="DGPType"/>
			<xs:element name="PERIOD_YEAR" type="DGYear"/>
			<xs:element name="C_STI_ORIG" type="DGc_dpi"/>
			<xs:element name="C_DOC_STAN" type="DGSTAN"/>
			<xs:element name="LINKED_DOCS" nillable="true" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="DOC" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="C_DOC" type="DGC_DOC"/>
									<xs:element name="C_DOC_SUB" type="DGC_DOC_SUB"/>
									<xs:element name="C_DOC_VER" type="DGC_DOC_VER"/>
									<xs:element name="C_DOC_TYPE" type="xs:nonNegativeInteger"/>
									<xs:element name="C_DOC_CNT" type="xs:nonNegativeInteger"/>
									<xs:element name="C_DOC_STAN" type="DGSTAN"/>
									<xs:element name="FILENAME" type="DGFilename"/>
								</xs:sequence>
								<xs:attribute name="NUM" type="xs:nonNegativeInteger" use="required"/>
								<xs:attribute name="TYPE" type="DGTypeLinkDoc" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
				<xs:unique name="UH_DOC_NUM">
					<xs:selector xpath="DOC"/>
					<xs:field xpath="@NUM"/>
				</xs:unique>
			</xs:element>
			<xs:element name="D_FILL" type="DGDate"/>
			<xs:element name="SOFTWARE" type="xs:string" nillable="true" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DBody">
		<xs:sequence>
			<!--HEAD-->
			<xs:choice>
				<xs:element name="HZ" type="DGchk"/>
				<xs:element name="HZU" type="DGchk"/>
			</xs:choice>
			<xs:element name="HDATE" type="DGDate" nillable="true" minOccurs="0"/>
			<xs:element name="HNUM" type="xs:positiveInteger" nillable="true" minOccurs="0"/>
			<xs:element name="HDATE1" type="DGDate"/>
			<xs:element name="HTIME1" type="xs:time"/>
			<xs:element name="HDATE2" type="DGDate"/>
			<xs:element name="HTIME2" type="xs:time"/>
			<xs:element name="HNUMREG" type="xs:positiveInteger" nillable="true" minOccurs="0"/>
			<xs:element name="HTIN" type="DGHTINJ"/>
			<xs:element name="HNAME" type="DGHNAME"/>
			<xs:element name="R07G1" type="xs:positiveInteger"/>
			<!--BODY-->
			<!--TABLE №1-->
			<xs:element name="T1RXXXXG1" type="DGI4nomColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG2" type="KOATUUColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG3S" type="StrColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG4" type="ChkColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG5S" type="StrColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG6S" type="StrColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG7" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG8" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG9" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG10" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T1RXXXXG11" type="Ozn2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<!--/TABLE №1-->
			<!--TABLE №2-->
			<xs:element name="T2RXXXXG1" type="DGI4nomColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG2" type="KOATUUColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG3S" type="StrColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG4" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG5" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T2RXXXXG6" type="Ozn2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<!--/TABLE №2-->
			<!--TABLE №3-->
			<xs:element name="T3RXXXXG1" type="DGI4nomColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG2" type="KOATUUColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG3S" type="StrColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG4S" type="StrColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG5" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG6" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T3RXXXXG7" type="Ozn2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<!--/TABLE №3-->
			<!--TABLE №4-->
			<xs:element name="T4RXXXXG1" type="DGI4nomColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG2" type="KOATUUColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG3S" type="StrColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG4" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T4RXXXXG5" type="Ozn2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<!--/TABLE №4-->
			<!--TABLE №5-->
			<xs:element name="T5RXXXXG1" type="DGI4nomColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG2" type="KOATUUColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG3S" type="StrColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG4" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG5" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG6" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG7" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG8" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG9" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T5RXXXXG10" type="Ozn2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<!--/TABLE №5-->
			<!--TABLE №6-->
			<xs:element name="T6RXXXXG1" type="DGI4nomColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T6RXXXXG2" type="KOATUUColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T6RXXXXG3S" type="StrColumn" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T6RXXXXG4" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T6RXXXXG5" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T6RXXXXG6" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T6RXXXXG7" type="Decimal2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<xs:element name="T6RXXXXG8" type="Ozn2Column" nillable="true" minOccurs="0" maxOccurs="9999"/>
			<!--/TABLE №6-->
			<!--FOOTER-->
			<xs:element name="HKEXECUTOR" type="DGDRFO_10"/>
			<xs:element name="HEXECUTOR" type="DGstring"/>
			<xs:element name="HPOST" type="DGstring"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== ealevchenko/FC/doc/medoc/28100024432974J0210401100000000110120202810 (1).XML
<?xml version="1.0" encoding="windows-1251"?>
<DECLAR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="J0210401.XSD">
  <DECLARHEAD>
    <TIN>24432974</TIN>
    <C_DOC>J02</C_DOC>
    <C_DOC_SUB>104</C_DOC_SUB>
    <C_DOC_VER>1</C_DOC_VER>
    <C_DOC_TYPE>0</C_DOC_TYPE>
    <C_DOC_CNT>1</C_DOC_CNT>
    <C_REG>28</C_REG>
    <C_RAJ>10</C_RAJ>
    <PERIOD_MONTH>1</PERIOD_MONTH>
    <PERIOD_TYPE>1</PERIOD_TYPE>
    <PERIOD_YEAR>2020</PERIOD_YEAR>
    <C_STI_ORIG>2810</C_STI_ORIG>
    <C_DOC_STAN>1</C_DOC_STAN>
    <LINKED_DOCS xsi:nil="true" />
    <D_FILL>05022020</D_FILL>
    <SOFTWARE>MEDOC</SOFTWARE>
  </DECLARHEAD>
  <DECLARBODY>
    <HZ>1</HZ>
    <HDATE1>01012020</HDATE1>
    <HTIME1>00:00:00</HTIME1>
    <HDATE2>31012020</HDATE2>
    <HTIME2>23:59:59</HTIME2>
    <HTIN>24432974</HTIN>
    <HNAME>ПУБЛІЧНЕ АКЦІОНЕРНЕ ТОВАРИСТВО"АРСЕЛОРМІТТАЛ КРИВИЙ РІГ"</HNAME>
    <R07G1>1005741</R07G1>
    <T1RXXXXG1 ROWNUM="1">1</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="2">2</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="3">3</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="4">4</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="5">5</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="6">6</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="7">7</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="8">8</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="9">9</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="10">10</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="11">11</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="12">12</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="13">13</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="14">14</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="15">15</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="16">16</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="17">17</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="18">18</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="19">19</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="20">20</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="21">21</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="22">22</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="23">23</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="24">24</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="25">25</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="26">26</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="27">27</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="28">28</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="29">29</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="30">30</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="31">31</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="32">32</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="33">33</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="34">34</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="35">35</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="36">36</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="37">37</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="38">38</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="39">39</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="40">40</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="41">41</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="42">42</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="43">43</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="44">44</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="45">45</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="46">46</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="47">47</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="48">48</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="49">49</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="50">50</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="51">51</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="52">52</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="53">53</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="54">54</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="55">55</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="56">56</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="57">57</T1RXXXXG1>
    <T1RXXXXG1 ROWNUM="58">58</T1RXXXXG1>
    <T1RXXXXG2 ROWNUM="1">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="2">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="3">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="4">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="5">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="6">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="7">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="8">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="9">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="10">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="11">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="12">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="13">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="14">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="15">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="16">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="17">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="18">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="19">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="20">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="21">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="22">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="23">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="24">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="25">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="26">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="27">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="28">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="29">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="30">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="31">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="32">2710194300</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="33" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="34" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="35" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="36" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="37" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="38" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="39">2710192100</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="40">2710192100</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="41">2710192100</T1RXXXXG2>
    <T1RXXXXG2 ROWNUM="42" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="43" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="44" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="45" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="46" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="47" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="48" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="49" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="50" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="51" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="52" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="53" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="54" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="55" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="56" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="57" xsi:nil="true" />
    <T1RXXXXG2 ROWNUM="58" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="1">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="2">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="3">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="4">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="5">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="6">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="7">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="8">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="9">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="10">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="11">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="12">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="13">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="14">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="15">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="16">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="17">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="18">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="19">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="20">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="21">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="22">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="23">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="24">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="25">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="26">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="27">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="28">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="29">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="30">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="31">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="32">Важкі дистиляти (газойлі)</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="33" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="34" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="35" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="36" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="37" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="38" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="39">Гас: паливо для реактивних двигунів</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="40">Гас: паливо для реактивних двигунів</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="41">Гас: паливо для реактивних двигунів</T1RXXXXG3S>
    <T1RXXXXG3S ROWNUM="42" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="43" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="44" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="45" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="46" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="47" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="48" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="49" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="50" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="51" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="52" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="53" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="54" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="55" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="56" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="57" xsi:nil="true" />
    <T1RXXXXG3S ROWNUM="58" xsi:nil="true" />
    <T1RXXXXG4 ROWNUM="1" xsi:nil="true" />
    <T1RXXXXG4 ROWNUM="2" xsi:nil="true" />
    <T1RXXXXG4 ROWNUM="3" xsi:nil="true" />
    <T1RXXXXG4 ROWNUM="4" xsi:nil="true" />
    <T1RXXXXG4 ROWNUM="5" xsi:nil="true" />
    <T1RXXXXG4 ROWNUM="6" xsi:nil="true" />
    <T1RXXXXG4 ROWNUM="7" xsi:nil="true" />
    <T1RXXXXG4 ROWNUM="8" xsi:nil="true" />
    <T1RXXXXG4 ROWNUM="9" xsi:nil="true" />
    <T1RXXXXG4 ROWNUM="10" xsi:nil="true" />
